### PR TITLE
Improved `permanentlyDeleteFile`.

### PR DESCRIPTION
**Pull request by Arkaeriit**
When some file in the trash did not have the
write permission, they could not be removed and
an error was raised.
Performing a chmod 700 on files about to be
removed fixes that issue.

### CODE REVIEW

**Comment by Arkaeriit** [comment]
BTW, the linter is unhappy but I don't find what the issue is on the logs.

**Comment by Arkaeriit** [comment]
After some more tests, the issue seems a bit deeper than just the files without write permission. I know that I had the issue when deleting some go packages. If I manage to reproduce it I will give some more details.

**Comment by quackduck** [comment]
Oh interesting

**Comment by Arkaeriit** [comment]
Here is the kind of error messages I can get:
```
o[^.^]o ~/dev/other >rem --empty -q
Warning, permanently deleting all files in /home/mbouillot/.local/share/rem/trash/trash
Confirm delete? (Y/n) > y
error: unlinkat /home/mbouillot/.local/share/rem/trash/trash/go/pkg/mod/golang.org/x/sys@v0.0.0-20210525143221-35b2ab0089ea/LICENSE: permission denied
```

**Comment by Arkaeriit** [comment]
I managed to reproduce the bug on a small scale. You can try it as well:
```
o[^.^]o ~ >mkdir a
o[^.^]o ~ >mkdir a/b
o[^.^]o ~ >touch a/b/c
o[^.^]o ~ >chmod 500 -R a/b/
o[^.^]o ~ >rem a
Trashed a
Undo using rem --undo "a"
o[^.^]o ~ >rem --empty
Warning, permanently deleting all files in /home/mbouillot/.local/share/rem/trash/trash
Confirm delete? (Y/n) > y
error: unlinkat /home/mbouillot/.local/share/rem/trash/trash/a/b/c: permission denied
```

**Comment by quackduck** [comment]
> After some more tests, the issue seems a bit deeper than just the files without write permission.


> Using the results of this PR, the issue is no more.


Wait so does this PR fix the go pkg issue?

**Comment by Arkaeriit** [comment]
Sorry if I was not very clear. This PR fixes a bug where some files could not be emptied from the trash. The issue seems to arise when there is nested files and directories without write permission.
I observed the bug the first time when cleaning go packages because those packages have a complex file structure. But the PR does nothing about the packages used in REM.
On the other hand, this PR does fixed the issue I had and let you cleanup Go packages.

**Comment by quackduck** [comment]
Okay, so with this PR there's no case in which the files cannot be deleted, correct?

**Comment by Arkaeriit** [comment]
Not as far as I know. But the Universe is full of surprises.

**Comment by quackduck** [comment]
lol

**Comment by Arkaeriit** [comment]
Wait, I did find a case were the file cannot be removed. When a file is not owned by the current user, the chow fails. I will try and fix this.

**Comment by Arkaeriit** [comment]
Should work now.

**Comment by quackduck** [comment]
Thanks!!!

**Pull request merged**
